#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# More detailed instructions are available at:
# https://carpentries.github.io/workshop-template/customization/index.html

# Which carpentry is this ("swc", or "rsg")?
# swc: Software Carpentry, standard bash, python, git using the lessons from the Southampton-RSG-Training git-org
# rsg: Custom Lessons from the Southampton-RSG-Training git-org
carpentry: "rsg"

# List Curriculum
# name is required branch is optional

# Specify that things in the episodes collection should be output.
collections:
  shell-novice:
    type: episode
    label: shell-novice
    branch: gh-pages
  git-novice:
    type: episode
    label: git-novice
    branch: gh-pages
  extras:
    output: true
    permalink: /:path/index.html
collections_dir: collections

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "python"

# If the workshop will be a lesson pilot (for a new official lesson or
# a lesson in The Carpentries Incubator), set pilot to "true".
pilot: false

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
# Most workshops don't use extra pages. More information about extra
# pages are included in the README:
# https://github.com/carpentries/workshop-template#creating-extra-pages
title: "Test Workshop Title"

#------------------------------------------------------------
# Incubator workshop settings (only relevant for workshops teaching a lesson
# in The Carpentries Incubator).
#
# For an Incubator workshop, uncomment the line below and add the URL of the lesson site.
# incubator_lesson_site: "put the URL of the lesson being taught here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your pre-workshop survey
# incubator_pre_survey: "put the URL of your pre-workshop survey here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your post-workshop survey
# incubator_post_survey: "put the URL of your post-workshop survey here"
#
#------------------------------------------------------------

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
# (Don't change this -- the contact address for your workshop will be set
# in the index.md file)
email: "team@carpentries.org"

#using the new jakyll remote themes
remote_theme: carpentries/carpentries-theme

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Surveys.
pre_survey: "https://carpentries.typeform.com/to/wi32rS?slug="
post_survey: "https://carpentries.typeform.com/to/UgVdRQ?slug="
instructor_pre_survey: "https://www.surveymonkey.com/r/instructor_training_pre_survey?workshop_id="
instructor_post_survey: "https://www.surveymonkey.com/r/instructor_training_post_survey?workshop_id="


# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/

# Turn on built-in syntax highlighting.
highlighter: rouge
